name: 'Common Aztec OTC Desk Setup'
description: 'Sets up Bun, Aztec, compiles, and optionally runs Sandbox & 2 PXEs'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22.20.0'
  start-sandbox:
    description: 'Whether to start the Aztec Sandbox'
    required: false
    default: 'false'
  start-api:
    description: 'Whether to start the Orderflow API'
    required: false
    default: 'false'

outputs:
  aztec-version:
    description: 'Detected Aztec version'
    value: ${{ steps.aztec-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Bun
      run: curl -fsSL https://bun.sh/install | bash
      shell: bash

    - name: Update path for Bun
      run: echo "$HOME/.bun/bin" >> $GITHUB_PATH
      shell: bash

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Detect Aztec version
      id: aztec-version
      run: |
        AZTEC_VERSION=$(node -p "require('./package.json').config.aztecVersion")
        echo "version=$AZTEC_VERSION" >> "$GITHUB_OUTPUT"
        echo "Aztec version is $AZTEC_VERSION"
      shell: bash

    - name: Install Aztec CLI
      run: |
        curl -s https://install.aztec.network > tmp.sh
        bash tmp.sh <<< yes "yes"
      shell: bash

    - name: Update path for Aztec
      run: echo "/home/runner/.aztec/bin" >> $GITHUB_PATH
      shell: bash

    - name: Set Aztec version
      run: |
        VERSION=${{ steps.aztec-version.outputs.version }} aztec-up
      shell: bash
    
    - name: Start Sandbox
      if: inputs.start-sandbox == 'true' && inputs.start-api == 'false'
      run: |
        bun run scripts/docker.ts sandbox &
      shell: bash
    
    - name: Start Sandbox and Orderflow API
      if: inputs.start-sandbox == 'true' && inputs.start-api == 'true'
      run: |
        bun run sandbox &
      shell: bash
    
    - name: Install project dependencies
      run: bun install
      shell: bash
  
    - name: Compile
      run: cd packages/contracts && bun run build
      shell: bash