
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractInstanceWithAddress, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import InvoiceRegistryContractArtifactJson from '../../../../target/otc_escrow-InvoiceRegistry.json' with { type: 'json' };
export const InvoiceRegistryContractArtifact = loadContractArtifact(InvoiceRegistryContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract InvoiceRegistry;
 */
export class InvoiceRegistryContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, InvoiceRegistryContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, InvoiceRegistryContract.artifact, wallet) as Promise<InvoiceRegistryContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<InvoiceRegistryContract>(PublicKeys.default(), wallet, InvoiceRegistryContractArtifact, InvoiceRegistryContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<InvoiceRegistryContract>(publicKeys, wallet, InvoiceRegistryContractArtifact, InvoiceRegistryContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof InvoiceRegistryContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<InvoiceRegistryContract['methods'][M]>
  ) {
    return new DeployMethod<InvoiceRegistryContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      InvoiceRegistryContractArtifact,
      InvoiceRegistryContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return InvoiceRegistryContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(InvoiceRegistryContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'private_invoices' | 'partial_notes' | 'token_addresses' | 'amounts' | 'title_hashes'> {
      return {
        private_invoices: {
      slot: new Fr(1n),
    },
partial_notes: {
      slot: new Fr(2n),
    },
token_addresses: {
      slot: new Fr(3n),
    },
amounts: {
      slot: new Fr(4n),
    },
title_hashes: {
      slot: new Fr(5n),
    }
      } as ContractStorageLayout<'private_invoices' | 'partial_notes' | 'token_addresses' | 'amounts' | 'title_hashes'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** _store_payment_info(invoice_id: field, partial_note: field, token_address: struct, amount: integer, title_hash: field) */
    _store_payment_info: ((invoice_id: FieldLike, partial_note: FieldLike, token_address: AztecAddressLike, amount: (bigint | number), title_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_invoice(invoice_id: field, title_hash: field, token_address: struct, amount: integer, metadata: field) */
    create_invoice: ((invoice_id: FieldLike, title_hash: FieldLike, token_address: AztecAddressLike, amount: (bigint | number), metadata: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_invoice(invoice_id: field) */
    get_invoice: ((invoice_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_payment_info(invoice_id: field) */
    get_payment_info: ((invoice_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_paid(invoice_id: field) */
    is_paid: ((invoice_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** pay_invoice(invoice_id: field, _nonce: field) */
    pay_invoice: ((invoice_id: FieldLike, _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
